displayName=CA Description Hider
author=playercoder1
description=Hides Combat Achievement task descriptions so you can guess the task from its name
tags=combat,achievements,ca,tasks,hide,spoiler
version=1.0
plugins=com.playercoder1.CaDescriptionHiderPlugin
build=standard